
import './globals.css';

// const poppins = Poppins({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Modal></Modal>
        <Navbar></Navbar> */}
        {children}
        {/* <Footer></Footer> */}
        <script src="../path/to/flowbite/dist/flowbite.min.js"></script>
      </body>
    </html>
  )
}

